/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceTestRouteImport } from './routes/voice-test'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as IndexRouteImport } from './routes/index'

const VoiceTestRoute = VoiceTestRouteImport.update({
  id: '/voice-test',
  path: '/voice-test',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/logs': typeof LogsRoute
  '/reports': typeof ReportsRoute
  '/scenarios': typeof ScenariosRoute
  '/settings': typeof SettingsRoute
  '/voice-test': typeof VoiceTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/logs': typeof LogsRoute
  '/reports': typeof ReportsRoute
  '/scenarios': typeof ScenariosRoute
  '/settings': typeof SettingsRoute
  '/voice-test': typeof VoiceTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/logs': typeof LogsRoute
  '/reports': typeof ReportsRoute
  '/scenarios': typeof ScenariosRoute
  '/settings': typeof SettingsRoute
  '/voice-test': typeof VoiceTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/config'
    | '/logs'
    | '/reports'
    | '/scenarios'
    | '/settings'
    | '/voice-test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/config'
    | '/logs'
    | '/reports'
    | '/scenarios'
    | '/settings'
    | '/voice-test'
  id:
    | '__root__'
    | '/'
    | '/config'
    | '/logs'
    | '/reports'
    | '/scenarios'
    | '/settings'
    | '/voice-test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigRoute: typeof ConfigRoute
  LogsRoute: typeof LogsRoute
  ReportsRoute: typeof ReportsRoute
  ScenariosRoute: typeof ScenariosRoute
  SettingsRoute: typeof SettingsRoute
  VoiceTestRoute: typeof VoiceTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice-test': {
      id: '/voice-test'
      path: '/voice-test'
      fullPath: '/voice-test'
      preLoaderRoute: typeof VoiceTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigRoute: ConfigRoute,
  LogsRoute: LogsRoute,
  ReportsRoute: ReportsRoute,
  ScenariosRoute: ScenariosRoute,
  SettingsRoute: SettingsRoute,
  VoiceTestRoute: VoiceTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
